name: py

on:
    schedule:
        - cron: '0 * * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: execute py script
              env:
                  B: ${{ secrets.B }}
                  S: ${{ secrets.S }}
                  T: ${{ secrets.T }}
                  U: ${{ secrets.U }}
                  Z: ${{ secrets.Z }}
              run: python3 sbd.py
